# fly.toml app configuration file generated for bicycle-marketplace on 2023-06-17T15:24:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bicycle-marketplace"
primary_region = "mia"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
